# Site settings
title: Alex Carpenter
email: your-email@domain.com
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/"
url: "http://ryanbennett.net"
fixedNav: 'true' # true or false
theme: grey # green, blue, orange, purple, grey
twitterUsername: hybrid_alex
githubUsername: alexcarpenter
dribbbleUsername:
codepenUsername:

# Build settings
permalink: /:year/:month/:title
markdown: kramdown
include: [_pages]
exclude: [_site, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed
